basePath: /api
definitions:
  client.SignInRequest:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  client.SignInResponse:
    properties:
      accessToken:
        type: string
      lastLogin:
        type: string
      refreshToken:
        type: string
    type: object
  client.TenantResponse:
    properties:
      address:
        type: string
      birthdate:
        type: string
      code:
        type: string
      description:
        type: string
      email:
        type: string
      firstName:
        type: string
      gender:
        $ref: '#/definitions/enum.Gender'
      identity:
        type: string
      lastName:
        type: string
      notes:
        type: string
      phone:
        type: string
      postalCode:
        type: string
      profileImage:
        type: string
      status:
        $ref: '#/definitions/enum.UserStatus'
      type:
        $ref: '#/definitions/enum.TenantType'
      userId:
        type: integer
    type: object
  client.TenantSignUpRequest:
    properties:
      address:
        type: string
      birthdate:
        type: string
      confirmPassword:
        type: string
      description:
        type: string
      email:
        type: string
      firstName:
        type: string
      gender:
        $ref: '#/definitions/enum.Gender'
      identity:
        type: string
      lastName:
        type: string
      password:
        type: string
      phone:
        type: string
      postalCode:
        type: string
      profileImage:
        type: string
      type:
        $ref: '#/definitions/enum.TenantType'
    required:
    - address
    - birthdate
    - confirmPassword
    - email
    - firstName
    - gender
    - identity
    - lastName
    - password
    - phone
    - postalCode
    - type
    type: object
  enum.Gender:
    enum:
    - MALE
    - FEMALE
    type: string
    x-enum-varnames:
    - MALE
    - FEMALE
  enum.TenantType:
    enum:
    - PERSONAL
    - BUSINESS
    - FOOD
    - BEVERAGE
    - FB
    type: string
    x-enum-varnames:
    - PERSONAL
    - BUSINESS
    - FOOD
    - BEVERAGE
    - FOOD_AND_BEVERAGE
  enum.UserStatus:
    enum:
    - ACTIVE
    - INACTIVE
    - PENDING
    - LOCKED
    - DELETED
    type: string
    x-enum-varnames:
    - ACTIVE
    - INACTIVE
    - PENDING
    - LOCKED
    - DELETED
host: localhost:8080
info:
  contact: {}
  description: API Documentation for FB Chain Management API - Developed by Ducking
    Team
  title: FB Chain Management API
  version: "1.0"
paths:
  /:
    get:
      responses: {}
      summary: Ping
  /auth/signin:
    post:
      consumes:
      - application/json
      parameters:
      - description: SignIn
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/client.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/client.SignInResponse'
        "400":
          description: Bad Request
          schema: {}
      summary: Sign in API
  /auth/signup/tenant:
    post:
      consumes:
      - application/json
      parameters:
      - description: TenantSignUp body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/client.TenantSignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/client.TenantResponse'
        "400":
          description: Bad Request
          schema: {}
      summary: Tenant sign up API
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
