basePath: /api
definitions:
  client.CompletedTenantRegisterRequest:
    properties:
      address:
        type: string
      description:
        type: string
      identity:
        type: string
      phone:
        type: string
      postalCode:
        type: string
      profileImage:
        type: string
      type:
        $ref: '#/definitions/enum.TenantType'
    required:
    - address
    - identity
    - phone
    - postalCode
    type: object
  client.InitialTenantRegisterRequest:
    properties:
      birthdate:
        type: string
      confirmPassword:
        type: string
      email:
        type: string
      firstName:
        type: string
      gender:
        $ref: '#/definitions/enum.Gender'
      lastName:
        type: string
      password:
        type: string
    required:
    - birthdate
    - confirmPassword
    - email
    - firstName
    - gender
    - lastName
    - password
    type: object
  client.SignInRequest:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  client.SignInResponse:
    properties:
      accessToken:
        type: string
      lastLogin:
        type: string
      refreshToken:
        type: string
    type: object
  client.UserResponse:
    properties:
      address:
        type: string
      birthdate:
        type: string
      email:
        type: string
      firstName:
        type: string
      gender:
        $ref: '#/definitions/enum.Gender'
      id:
        type: integer
      identity:
        type: string
      lastName:
        type: string
      phone:
        type: string
      postalCode:
        type: string
      profileImage:
        type: string
      role:
        $ref: '#/definitions/enum.Role'
      status:
        $ref: '#/definitions/enum.UserStatus'
    type: object
  enum.Gender:
    enum:
    - MALE
    - FEMALE
    type: string
    x-enum-varnames:
    - MALE
    - FEMALE
  enum.Role:
    enum:
    - ADMIN
    - MANAGER
    - STAFF
    - TENANT
    type: string
    x-enum-varnames:
    - ADMIN
    - MANAGER
    - STAFF
    - TENANT
  enum.TenantType:
    enum:
    - PERSONAL
    - BUSINESS
    - FOOD
    - BEVERAGE
    - FB
    type: string
    x-enum-varnames:
    - PERSONAL
    - BUSINESS
    - FOOD
    - BEVERAGE
    - FOOD_AND_BEVERAGE
  enum.UserStatus:
    enum:
    - ACTIVE
    - INACTIVE
    - PENDING
    - LOCKED
    - DELETED
    type: string
    x-enum-varnames:
    - ACTIVE
    - INACTIVE
    - PENDING
    - LOCKED
    - DELETED
host: localhost:8080
info:
  contact: {}
  description: API Documentation for FB Chain Management API - Developed by Ducking
    Team
  title: FB Chain Management API
  version: "1.0"
paths:
  /:
    get:
      responses: {}
      summary: Ping
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: SignIn
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/client.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/client.SignInResponse'
        "400":
          description: Bad Request
          schema: {}
      summary: Sign in API
  /auth/register/tenant/completed:
    post:
      consumes:
      - application/json
      parameters:
      - description: CompletedTenantRegister body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/client.CompletedTenantRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/client.UserResponse'
        "400":
          description: Bad Request
          schema: {}
      security:
      - BearerAuth: []
      summary: Completed tenant register API
  /auth/register/tenant/initial:
    post:
      consumes:
      - application/json
      parameters:
      - description: InitialTenantRegister body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/client.InitialTenantRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/client.UserResponse'
        "400":
          description: Bad Request
          schema: {}
      summary: Intial tenant sign up API
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
