basePath: /api
definitions:
  client.CreateRestaurantRequest:
    properties:
      contactEmail:
        type: string
      contactPhone:
        type: string
      description:
        type: string
      image:
        items:
          type: string
        type: array
      location:
        type: string
      name:
        type: string
      notes:
        type: string
      postalCode:
        type: string
      type:
        type: string
    required:
    - location
    - name
    - notes
    - postalCode
    - type
    type: object
  client.CreateSubPackageRequest:
    properties:
      description:
        type: string
      durationMonth:
        type: integer
      image:
        type: string
      name:
        type: string
      price:
        type: string
    required:
    - durationMonth
    - name
    - price
    type: object
  client.OrderResponse:
    properties:
      amount:
        type: number
      id:
        type: integer
      orderDate:
        type: string
      restaurantId:
        type: integer
      status:
        $ref: '#/definitions/enum.OrderStatus'
      tenantId:
        type: integer
    type: object
  client.PaySubPackageRequest:
    properties:
      restaurantId:
        type: integer
      subPackageId:
        type: integer
    required:
    - restaurantId
    - subPackageId
    type: object
  client.RestaurantResponse:
    properties:
      avgRating:
        type: number
      contactEmail:
        type: string
      contactPhone:
        type: string
      description:
        type: string
      id:
        type: integer
      images:
        items:
          type: string
        type: array
      location:
        type: string
      name:
        type: string
      notes:
        type: string
      postalCode:
        type: string
      subPackageId:
        type: integer
      tenantId:
        type: integer
      type:
        type: string
    type: object
  client.SignInRequest:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  client.SignInResponse:
    properties:
      accessToken:
        type: string
      lastLogin:
        type: string
      refreshToken:
        type: string
    type: object
  client.SubPackageResponse:
    properties:
      description:
        type: string
      durationMonth:
        type: integer
      id:
        type: integer
      image:
        type: string
      isActive:
        type: boolean
      name:
        type: string
      price:
        type: number
    type: object
  client.TenantResponse:
    properties:
      address:
        type: string
      birthdate:
        type: string
      code:
        type: string
      description:
        type: string
      email:
        type: string
      firstName:
        type: string
      gender:
        $ref: '#/definitions/enum.Gender'
      identity:
        type: string
      lastName:
        type: string
      notes:
        type: string
      phone:
        type: string
      postalCode:
        type: string
      profileImage:
        type: string
      status:
        $ref: '#/definitions/enum.UserStatus'
      type:
        $ref: '#/definitions/enum.TenantType'
      userId:
        type: integer
    type: object
  client.TenantSignUpRequest:
    properties:
      address:
        type: string
      birthdate:
        type: string
      confirmPassword:
        type: string
      description:
        type: string
      email:
        type: string
      firstName:
        type: string
      gender:
        $ref: '#/definitions/enum.Gender'
      identity:
        type: string
      lastName:
        type: string
      password:
        type: string
      phone:
        type: string
      postalCode:
        type: string
      profileImage:
        type: string
      type:
        $ref: '#/definitions/enum.TenantType'
    required:
    - address
    - birthdate
    - confirmPassword
    - email
    - firstName
    - gender
    - identity
    - lastName
    - password
    - phone
    - postalCode
    - type
    type: object
  client.UpdateProfileRequest:
    properties:
      address:
        type: string
      birthdate:
        type: string
      firstName:
        type: string
      gender:
        $ref: '#/definitions/enum.Gender'
      identity:
        type: string
      lastName:
        type: string
      phone:
        type: string
      postalCode:
        type: string
      profileImage:
        type: string
    type: object
  client.UserResponse:
    properties:
      address:
        type: string
      birthdate:
        type: string
      email:
        type: string
      firstName:
        type: string
      gender:
        $ref: '#/definitions/enum.Gender'
      id:
        type: integer
      identity:
        type: string
      lastName:
        type: string
      phone:
        type: string
      postalCode:
        type: string
      profileImage:
        type: string
      role:
        $ref: '#/definitions/enum.Role'
      status:
        $ref: '#/definitions/enum.UserStatus'
    type: object
  client.VerifyChangePasswordRequest:
    properties:
      verifiedCode:
        type: string
    required:
    - verifiedCode
    type: object
  enum.Gender:
    enum:
    - MALE
    - FEMALE
    type: string
    x-enum-varnames:
    - GENDER_MALE
    - GENDER_FEMALE
  enum.OrderStatus:
    enum:
    - PENDING
    - COMPLETED
    - CANCELED
    type: string
    x-enum-varnames:
    - ORDER_PENDING
    - ORDER_COMPLETED
    - ORDER_CANCELED
  enum.Role:
    enum:
    - ADMIN
    - MANAGER
    - STAFF
    - TENANT
    type: string
    x-enum-varnames:
    - ROLE_ADMIN
    - ROLE_MANAGER
    - ROLE_STAFF
    - ROLE_TENANT
  enum.TenantType:
    enum:
    - PERSONAL
    - BUSINESS
    - FOOD
    - BEVERAGE
    - FB
    type: string
    x-enum-varnames:
    - TENANT_PERSONAL
    - TENANT_BUSINESS
    - RESTAURANT_FOOD
    - RESTAURANT_BEVERAGE
    - RESTAURANT_FOOD_AND_BEVERAGE
  enum.UserStatus:
    enum:
    - ACTIVE
    - INACTIVE
    - PENDING
    - LOCKED
    - DELETED
    type: string
    x-enum-varnames:
    - USER_ACTIVE
    - USER_INACTIVE
    - USER_PENDING
    - USER_LOCKED
    - USER_DELETED
host: localhost:8080
info:
  contact: {}
  description: API Documentation for FB Chain Management API - Developed by Ducking
    Team
  title: FB Chain Management API
  version: "1.0"
paths:
  /admin/subscription:
    post:
      consumes:
      - application/json
      parameters:
      - description: CreateSubPackage body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/client.CreateSubPackageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/client.SubPackageResponse'
        "400":
          description: Bad Request
          schema: {}
      security:
      - BearerAuth: []
      summary: Create subscription package API
  /auth/change-password/verify:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
      security:
      - BearerAuth: []
      summary: Get change password OTP API
    post:
      consumes:
      - application/json
      parameters:
      - description: VerifyChangePassword body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/client.VerifyChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
      security:
      - BearerAuth: []
      summary: Verify change password OTP API
  /auth/signin:
    post:
      consumes:
      - application/json
      parameters:
      - description: SignIn body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/client.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/client.SignInResponse'
        "400":
          description: Bad Request
          schema: {}
      summary: Sign in API
  /auth/signup/tenant:
    post:
      consumes:
      - application/json
      parameters:
      - description: TenantSignUp body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/client.TenantSignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/client.TenantResponse'
        "400":
          description: Bad Request
          schema: {}
      summary: Tenant sign up API
  /profile:
    patch:
      consumes:
      - application/json
      parameters:
      - description: UpdateProfile body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/client.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/client.UserResponse'
        "400":
          description: Bad Request
          schema: {}
      security:
      - BearerAuth: []
      summary: Change Profile API
  /tenant/order:
    post:
      consumes:
      - application/json
      parameters:
      - description: PaySubPackage body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/client.PaySubPackageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/client.OrderResponse'
        "400":
          description: Bad Request
          schema: {}
      security:
      - BearerAuth: []
      summary: Pay subscription package API
  /tenant/restaurant:
    post:
      consumes:
      - application/json
      parameters:
      - description: CreateRestaurant body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/client.CreateRestaurantRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/client.RestaurantResponse'
        "400":
          description: Bad Request
          schema: {}
      security:
      - BearerAuth: []
      summary: Create restaurant API
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
